quarkus.application.name=PersonalMCPServer
quarkus.http.port=8081

github.token=${GITHUB_TOKEN:TOKEN}

quarkus.log.category."com.bevilacqua1996.mcpServerPersonal".level=DEBUG

# MCP Server Configuration
quarkus.mcp.server.http.root-path=/api/mcp
quarkus.mcp.server.server-info.name=PersonalMCPServer
quarkus.mcp.server.server-info.version=0.0.1-SNAPSHOT
quarkus.mcp.server.server-info.title=Personal MCP Server
